### ISSUE TITLE
Class 'cinghie\userextended\models\User' not found

### ISSUE THREAD

**Issue by kholmatov** [cinghie/yii2-user-extended#14]
`1. in /app/vendor/dektrium/yii2-user/Bootstrap.php at line 57
48495051525354555657585960616263646566        if ($app->hasModule('user') && ($module = $app->getModule('user')) instanceof Module) {
            $this->_modelMap = array_merge($this->_modelMap, $module->modelMap);
            foreach ($this->_modelMap as $name => $definition) {
                $class = "dektrium\\user\\models\\" . $name;
                Yii::$container->set($class, $definition);
                $modelName = is_array($definition) ? $definition['class'] : $definition;
                $module->modelMap[$name] = $modelName;
                if (in_array($name, ['User', 'Profile', 'Token', 'Account'])) {
                    Yii::$container->set($name . 'Query', function () use ($modelName) {
                        return $modelName::find();
                    });
                }
            }
 
            Yii::$container->setSingleton(Finder::className(), [
                'userQuery'    => Yii::$container->get('UserQuery'),
                'profileQuery' => Yii::$container->get('ProfileQuery'),
`

**Comment by cinghie** [comment]
Hi @kholmatov,

have you configured correctly yii2-user on your config.php?

Check https://github.com/cinghie/yii2-user-extended#5-set-configuration-file

**Comment by SwapnilAkolkar** [comment]
Hi Cinghie,
Thank you for this module I am using Yii2 advanced template how can I put modules n other config settings in config file. Cause I confused with 3 config files in frontend , backend and in common.
Thanking You

**Comment by SwapnilAkolkar** [comment]
Here is my some error log when I try to putting config in common and frontend local-main.php
An Error occurred while handling another error:
yii\base\InvalidArgumentException: Invalid path alias: @dektrium/user/views/admin in C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\BaseYii.php:154
Stack trace:
#0 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\Theme.php(144): yii\BaseYii::getAlias('@dektrium/user/...')
#1 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\View.php(228): yii\base\Theme->applyTo('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\web\ErrorHandler.php(269): yii\base\View->renderFile('C:\\xampp\\htdocs...', Array, Object(yii\web\ErrorHandler))
#3 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\web\ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#4 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidConfigException))
#5 [internal function]: yii\base\ErrorHandler->handleException(Object(yii\base\InvalidConfigException))
#6 {main}
Previous exception:
ReflectionException: Class dektrium\rbac\Module does not exist in C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\di\Container.php:431
Stack trace:
#0 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\di\Container.php(431): ReflectionClass->__construct('dektrium\\rbac\\M...')
#1 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\di\Container.php(365): yii\di\Container->getDependencies('dektrium\\rbac\\M...')
#2 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('dektrium\\rbac\\M...', Array, Array)
#3 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('dektrium\\rbac\\M...', Array, Array)
#4 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\Module.php(427): yii\BaseYii::createObject(Array, Array)
#5 C:\xampp\htdocs\yii2userbasic\vendor\dektrium\yii2-rbac\Bootstrap.php(68): yii\base\Module->getModule('rbac')
#6 C:\xampp\htdocs\yii2userbasic\vendor\dektrium\yii2-rbac\Bootstrap.php(42): dektrium\rbac\Bootstrap->checkRbacModuleInstalled(Object(yii\web\Application))
#7 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\Application.php(297): dektrium\rbac\Bootstrap->bootstrap(Object(yii\web\Application))
#8 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\web\Application.php(69): yii\base\Application->bootstrap()
#9 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\Application.php(273): yii\web\Application->bootstrap()
#10 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\base\Application->init()
#11 C:\xampp\htdocs\yii2userbasic\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#12 C:\xampp\htdocs\yii2userbasic\frontend\web\index.php(17): yii\base\Application->__construct(Array)
#13 {main}
